### PR TITLE
Trigger actions update

### LINKED ISSUE #5: Is dataset updated?
https://github.com/tc39/dataset/tree/gh-pages
last commit is last month.

proposal repo is updated yesterday.
https://github.com/tc39/proposals

Probably, the reason is https://github.com/tc39/dataset/actions/workflows/follow.yml action has beed stopped.

>  This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days.

### PR DESCRIPTION
**Pull request by Jack-Works**
close #5

### CODE REVIEW

**Comment by ljharb** [comment]
For future reference, GitHub emails repo collabs before shutting off automated workflows, and any of them can click the link in that email to reset the clock.

**Comment by azu** [comment]
Can somebody click continue button?
https://github.com/tc39/dataset/actions/workflows/follow.yml

**Comment by Jack-Works** [comment]
@septs please

**Comment by azu** [comment]
https://github.com/tc39/dataset/actions/workflows/follow.yml
It is still stopped.

**Comment by Jack-Works** [comment]
@septs hi can you fix this?

**Pull request merged**
